# ansible-playbook ./setup.yml  -v -vvvv -u ubuntu -i ./host.yml 
---
- name: Hello World!
  hosts: [nodes]
  become: yes
  user: vagrant

  tasks:
 
  - fail: msg="===>> Only on CentOS 7, derivatives, and later ! <<==="
    when: ansible_distribution != "CentOS" or ansible_distribution_major_version != "7"
  - name: Hello World!
    shell: echo "Hi! Tower is working."
  - name: Yum update standard repo
    yum: name=* state=latest update_cache=yes
  - name: write our hosts
    template: src=/vagrant/hosts.j2 dest=/etc/hosts mode=644 owner=root group=root
  - name: Install packages
    yum: name={{ item }} state=present
    with_items:
      - rng-tools
      - ipa-server
      - ipa-server-dns
      - bind
      - bind-dyndb-ldap
      - vim
      - lsof
      - lynx
      - nmap
      - firewalld
      - bind-utils
      - dos2unix
      - sshpass
  - name: Mise en forme unix des script
    lineinfile:
      path: /usr/lib/systemd/system/rngd.service
      regexp: '^ExecStart=/sbin/rngd -f'
      line: 'ExecStart=/sbin/rngd -f -r /dev/urandom -o /dev/random'
  - name: Démarrage du service rngd sur la vm pour rendre actif le générateur aléatoire.
    systemd:
      state: started
      daemon_reload: yes
      enabled: yes
      name: rngd      
  - name: Mise en forme unix des script
    shell: dos2unix /vagrant/install-*
  - name: Ensure NetworkManager does not change /etc/resolf.conf
    ini_file:
      path: /etc/NetworkManager/NetworkManager.conf
      section: main
      option: dns
      value: none
      backup: yes
  - name: stop chronyd
    service: name=chronyd state=stopped enabled=false      
