# ansible-playbook ./setup.yml  -v -vvvv -u ubuntu -i ./host.yml 
---
- name: Hello World!
  hosts: [nodes]
  become: yes
  user: vagrant

  tasks:
 
  - fail: msg="===>> Only on CentOS 7, derivatives, and later ! <<==="
    when: ansible_distribution != "CentOS" or ansible_distribution_major_version != "7"
  - name: Hello World!
    shell: echo "Hi! Tower is working."
  - name: Yum update standard repo
    yum: name=* state=latest update_cache=yes
  - name: write our hosts
    template: src=/vagrant/hosts.j2 dest=/etc/hosts mode=644 owner=root group=root
