# ansible-playbook ./setup.yml  -v -vvvv -u ubuntu -i ./host.yml 
# cd /vagrant && ansible-playbook /vagrant/provision.yml  -vvv -i /vagrant/inventory.txt  -l nodes
---
- name: Playbook de test de monté de version de FreeIPA
  hosts: [nodes]
  become: yes
  user: vagrant

  environment:

    IPA_SERVER_PASSWORD: Welcome1
    IPA_SERVER_NAME: node1
    IPA_SERVER_DOMAIN: jobjects.org
    IPA_SERVER_IP: 192.168.56.141
    # IPA_SERVER_NTP: ntp1.net-courrier.extra.laposte.fr
    IPA_SERVER_NTP: 0.fr.pool.ntp.org

  tasks:
 
  - name: Doit être CentOS7
    fail: msg="===>> Only on CentOS 7, derivatives, and later ! <<==="
    when: (ansible_distribution != "CentOS" and ansible_distribution != 'Red Hat Enterprise Linux') or (ansible_distribution_major_version != "7")
#  - name: Yum update standard repo
#    yum: name=* state=latest update_cache=yes
  - name: Ecriture du fichier /etc/hosts
    template: src=/vagrant/hosts.j2 dest=/etc/hosts mode=644 owner=root group=root
  - name: Ecriture du fichier /etc/resolv.conf
    template: src=/vagrant/resolv.conf.j2 dest=/etc/resolv.conf mode=644 owner=root group=root    
  - name: Installation des packages
    yum: name={{ item }} state=present update_cache=yes
    with_items:
      - rng-tools
      - ipa-server
      - ipa-server-dns
      - bind
      - bind-dyndb-ldap
      - vim
      - lsof
      - lynx
      - nmap
      - firewalld
      - bind-utils
      - dos2unix
      - sshpass
  - name: Mise en forme unix des script
    lineinfile:
      path: /usr/lib/systemd/system/rngd.service
      regexp: '^ExecStart=/sbin/rngd -f'
      line: 'ExecStart=/sbin/rngd -f -r /dev/urandom -o /dev/random'
  - name: Démarrage du service rngd sur la vm pour rendre actif le générateur aléatoire.
    systemd:
      state: started
      daemon_reload: yes
      enabled: yes
      name: rngd      
  - name: Mise en forme unix des script
    shell: dos2unix /vagrant/install-*
  - name: Ensure NetworkManager does not change /etc/resolf.conf
    ini_file:
      path: /etc/NetworkManager/NetworkManager.conf
      section: main
      option: dns
      value: none
      backup: yes
  - name: Extinction et déactivation de chronyd pour laisser la place à ntpd
    service: name=chronyd state=stopped enabled=false      
  - name: Mise à jour du l'heure
    # shell: ntpdate -su $IPA_SERVER_NTP
    shell: echo $IPA_SERVER_NTP
    register: result
  - name: Affichage de l'heure
    debug:
      msg: "Heure: {{ result }}"
  - name: FreeIPA Master
    #shell: ipa-server-install --admin-password=$IPA_SERVER_PASSWORD --ds-password=$IPA_SERVER_PASSWORD  --hostname=$IPA_SERVER_NAME.$IPA_SERVER_DOMAIN --ip-address=$IPA_SERVER_IP --domain=$IPA_SERVER_DOMAIN --realm=${IPA_SERVER_DOMAIN^^} --mkhomedir --setup-dns --forwarder=145.42.2.2 --forwarder=165.162.68.19 --auto-reverse --ssh-trust-dns --unattended
    shell: ipa-server-install --admin-password=$IPA_SERVER_PASSWORD --ds-password=$IPA_SERVER_PASSWORD  --hostname=$IPA_SERVER_NAME.$IPA_SERVER_DOMAIN --ip-address=$IPA_SERVER_IP --domain=$IPA_SERVER_DOMAIN --realm=${IPA_SERVER_DOMAIN^^} --mkhomedir --setup-dns --forwarder=8.8.8.8 --forwarder=8.8.4.4 --auto-reverse --ssh-trust-dns --unattended
    when: "'idmmaster' in group_names"
  - name: FreeIPA Secondary
    shell: ipa-replica-install --principal admin --admin-password $IPA_SERVER_PASSWORD --server $IPA_SERVER_NAME.$IPA_SERVER_DOMAIN --domain=$IPA_SERVER_DOMAIN --setup-ca --unattended
    when: "'idmsecondary' in group_names"
  - name: FreeIPA Client
    shell: ipa-client-install --hostname=`hostname -f` --server=$IPA_SERVER_NAME.$IPA_SERVER_DOMAIN --domain=$IPA_SERVER_DOMAIN --ntp-server=$IPA_SERVER_NTP -U -p admin -w $IPA_SERVER_PASSWORD
    # authconfig --enablemkhomedir --update
    when: "'idmclient' in group_names"
