# ansible-playbook ./setup.yml  -v -vvvv -u ubuntu -i ./host.yml 
# cd /vagrant && ansible-playbook /vagrant/provision.yml  -vvv -i /vagrant/inventory.txt  -l nodes
---
- name: Playbook de test de monté de version de FreeIPA
  hosts: [nodes]
  become: yes
  user: vagrant

  environment:

    IPA_SERVER_PASSWORD: Welcome1
    IPA_SERVER_NAME: node1
    IPA_SERVER_DOMAIN: jobjects.net
    IPA_SERVER_IP: 192.168.56.141
    IPA_SERVER_NTP: 0.fr.pool.ntp.org

  tasks:
 
  - name: Doit être Debian
    fail: msg="===>> Only on Debian, derivatives, and later ! <<==="
    when: (ansible_distribution != "Debian")
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Upgrade all packages on servers
    apt: upgrade=dist force_apt_get=yes

  - name: Ecriture du fichier /etc/hosts
    template: src=/vagrant/hosts.j2 dest=/etc/hosts mode=644 owner=root group=root
  - name: Ecriture du fichier /etc/resolv.conf
    template: src=/vagrant/resolv.conf.j2 dest=/etc/resolv.conf mode=644 owner=root group=root    
  - name: Installation des packages
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - vim
      - lsof
      - lynx
      - nmap
      - firewalld
      - bind-utils
      - dos2unix
      - sshpass
  - name: Mise en forme unix des script
    lineinfile:
      path: /usr/lib/systemd/system/rngd.service
      regexp: '^ExecStart=/sbin/rngd -f'
      line: 'ExecStart=/sbin/rngd -f -r /dev/urandom -o /dev/random'
  - name: Démarrage du service rngd sur la vm pour rendre actif le générateur aléatoire.
    systemd:
      state: started
      daemon_reload: yes
      enabled: yes
      name: rngd      
  - name: Mise en forme unix des script
    shell: dos2unix /vagrant/install-*
  - name: Ensure NetworkManager does not change /etc/resolf.conf
    ini_file:
      path: /etc/NetworkManager/NetworkManager.conf
      section: main
      option: dns
      value: none
      backup: yes
  - name: Extinction et déactivation de chronyd pour laisser la place à ntpd
    service: name=chronyd state=stopped enabled=false      
  - name: Mise à jour du l'heure
    shell: ntpdate -su $IPA_SERVER_NTP
    register: result
  - name: Affichage de l'heure
    debug:
      msg: "Heure: {{ result }}"
  - name: FreeIPA Master
    shell: /vagrant/install-freeipa.sh
    when: "'idmmaster' in group_names"
  - name: FreeIPA Secondary
    shell: /vagrant/install-replica.sh
    when: "'idmsecondary' in group_names"
  - name: FreeIPA Client
    shell: /vagrant/install-client.sh
    when: "'idmclient' in group_names"
